### ISSUE TITLE
Loading glitch on page refresh

### ISSUE THREAD

**Issue by lorentzfb** [kuuji/button-card#8]
This shows up for a few seconds on when page is refreshed or loads for the first time. Can this be avoided?

![error](https://user-images.githubusercontent.com/29151133/44990220-a6990e00-af90-11e8-97fa-2a6dc318d071.png)

**Comment by kuuji** [comment]
I'm not sure. All of the Lovelace "modules" that I use do that. The scripts do not.
It looks like an issue in the way Lovelace loads the modules.

^ I'm referring to the type when you include the card resources in ui-lovelace.yaml. This is a `module`, the problem doesn't occur for cards that have a `js` type.

Have you tried searching in the forum? I haven't had time to look into that yet. I'd appreciate some help in debugging this ;)

**Comment by dustins1983** [comment]
I had this same issue when I first started using this card which was a few days ago. I have several custom items in lovelace and the button car was my last. I thought as a shot in the dark maybe since its listed last, it loads last?

So i ordered it second and it has not done it since. The only other thing I did was eliminate one custom card I am not currently using. My love lace looks like this now:

resources:
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/simple-thermostat/simple-thermostat.js?v=1
    type: module
  - url: /local/button-card.js
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.3
    type: js  
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  #- url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=0.1.1
    #type: module
  #- url: /local/surveillance-card.js?v=0.0.1
    #type: module

All modules have always worked without this issue. I did # out the surveillance card at the same time.

I dont know if its just dumb luck, but like i said, its been fine since that change.
